### ISSUE TITLE
HTTP Response Code 409

### ISSUE THREAD

**Issue by gregsuzy** [osisoft/OMF-Docs#48]
The following http status codes should be added to the list of possible status codes returned by OSIsoft products accepting OMF messages over HTTP:

HTTP/1.1 409 Conflict - Returned when sending a data message which tries to create static data that has already been created.

HTTP/1.1 501 Not Implemented - Returned when trying to use action=update to update static data that has already been created.

**Comment by cmanhard** [comment]
201, 404, 409, and 501 codes added to the 1.2 specification
